name: "tests"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
env:
  tests_timeout: "2h"
  golangci_lint_version: "v1.26"
jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26

      - name: "Download terraform k8s provider"
        run: |
          wget https://github.com/banzaicloud/terraform-provider-k8s/releases/download/v0.7.7/terraform-provider-k8s_0.7.7_linux_amd64.tar.gz
          tar xvzf terraform-provider-k8s_0.7.7_linux_amd64.tar.gz && chmod +x terraform-provider-k8s
          mkdir -p ~/.terraform.d/plugins
          mv terraform-provider-k8s ~/.terraform.d/plugins

      - name: "go vet"
        run: go vet ./...

      - name: "go providerlint"
        run: |
          go get github.com/bflad/tfproviderlint/cmd/tfproviderlint
          ~/go/bin/tfproviderlint ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Optional: golangci-lint command line arguments.
          args: --timeout=3m0s
          version: ${{ env.golangci_lint_version }}

      - name: "install k3s"
        env:
          K3S_KUBECONFIG_MODE: 644
          KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
        run: |
          curl -sfL https://get.k3s.io | sh -s - --disable traefik --disable servicelb
          kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

      - name: "install kubeflow"
        env:
          KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./tests/kubeflow_setup

      - name: "Wait for service to be available"
        env:
          KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
        run: |
          while [[ "$(kubectl get pod -n kubeflow -l app=ml-pipeline | grep Running | wc -l)" -ne "1" ]]; do echo "Waiting for service to be available";  sleep 5; done

      - name: "Run acceptance tests"
        env:
          KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
        run: |
          kubectl port-forward svc/ml-pipeline -n kubeflow 8080:8888 &
          while ! [[ $(curl -ss http://localhost:8080/apis/v1beta1/experiments) ]]; do echo "Waiting for service to be available";  sleep 5; done
          make testacc

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov

      - name: Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
